modules/purchase/models/PurchaseOrder.php
<?php

namespace app\modules\purchase\models;

use app\modules\parties\models\Contact;
use \DateTime;

/**
 * This is the model class for table "tbl_purchaseorder".
 *
 * @property integer $id
 * @property integer $contact_id
 * @property string $order_number
 * @property integer $creator_id
 * @property integer $time_deleted
 * @property integer $time_create
 *
 * @property Party $party
 * @property Purchaseordergroup[] $purchaseordergroups
 */
class PurchaseOrder extends \yii\db\ActiveRecord
{
  
	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'tbl_purchaseorder';
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['contact_id'], 'required'],
			[['contact_id', 'creator_id', 'time_deleted', 'time_create','approver_id'], 'integer'],
			[['order_number'], 'string', 'max' => 200],
      [['status'], 'string', 'max' => 200],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id'           => \Yii::t('app','ID'),
			'contact_id'   => \Yii::t('app','Main Entity'),
			'order_number' => \Yii::t('app','Order Number'),
			'creator_id'   => \Yii::t('app','Creator ID'),
      'approver_id'   => \Yii::t('app','Approval by'),
			'time_deleted' => \Yii::t('app','Time Deleted'),
			'time_create'  => \Yii::t('app','Time Create'),
		];
	}

	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getContact()
	{
		return $this->hasOne(Contact::className(), ['id' => 'contact_id']);
	}

	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getPurchaseordergroups()
	{
		return $this->hasMany(PurchaseOrderGroup::className(), ['purchaseorder_id' => 'id']);
	}

	/**
	 * [beforeSave description]
	 * @param  [type] $insert [description]
	 * @return [type]         [description]
	 */
	public function beforeSave($insert)
  {
    $date = new DateTime('now');
    if($this->isNewRecord)
    {
      if(\Yii::$app->user->isGuest)
      {
        $this->creator_id = 0; //external system writer
      }
      else
      {
        $this->creator_id = \Yii::$app->user->identity->id;
      }      
    }
    if(is_null($this->time_create))
    {
      $this->time_create = $date->format("U");
    }
    return parent::beforeSave($insert);
  }
}

modules/purchase/controllers/PurchaseOrderController.php
<?php

namespace app\modules\purchase\controllers;

use Yii;
use app\modules\app\controllers\AppController;

use app\modules\purchase\models\PurchaseOrder;
use app\modules\purchase\models\PurchaseOrderSearch;
use yii\db\Query;
use yii\data\ArrayDataProvider;
use yii\web\NotFoundHttpException;
use yii\web\VerbFilter;
use yii\helpers\Json;
use yii\helpers\Html;
use yii\helpers\Url;

use app\modules\purchase\models\PurchaseOrderGroup;

use DateTime;
/**
 * PurchaseOrderController implements the CRUD actions for PurchaseOrder model.
 */
class PurchaseOrderController extends AppController
{

	public function behaviors()
	{
		return [
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['get'],
				],
			],
			'AccessControl' => [
				'class' => '\yii\web\AccessControl',
				'rules' => [
					[
						'allow'=>true,
						'actions'=>['importer'],
						'roles'=>['?'],
					],
					array(
						'allow'=>true,
						'actions'=>array('update','create','index','view','delete','dhtmlxgrid','create-request','window','workflow','windowoperations'),
				    'roles'=>array('@'),
					),  
					array(
						'allow'=>false,  // deny all users
					),
				]
			]
		];
	}

	/**
	 * Lists all PurchaseOrder models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new PurchaseOrderSearch;
		$dataProvider = $searchModel->search($_GET);

		return $this->render('index', [
			'dataProvider' => $dataProvider,
			'searchModel' => $searchModel,
		]);
	}

	/**
	 * Displays a single PurchaseOrder model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView($id)
	{
		return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	 * Creates a new PurchaseOrder model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate()
	{
		$model = new PurchaseOrder;

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			return $this->redirect(['view', 'id' => $model->id]);
		} else {
			return $this->render('create', [
				'model' => $model,
			]);
		}
	}

  public function actionCreateRequest()
  {
    //change layout
    $this->layout = '/main';

    $model = new PurchaseOrder;
    $model->contact_id = \Yii::$app->user->CurrentContactId;
    
    if($model->save())
    {
    	$groupModel = new PurchaseOrderGroup;
    	$groupModel->contact_id = \Yii::$app->user->CurrentContactId;
 			$groupModel->purchaseorder_id = $model->id;
 			$groupModel->save();
   		return $this->redirect(['update', 'id' => $model->id]);
   	}else{
   		throw new NotFoundHttpException('The model cant be created.');
   	}
  }

  /**
	 * [actionWindow description]
	 * @param  [type] $id  [description]
	 * @param  [type] $win [description]
	 * @return [type]      [description]
	 */
	public function actionWindow($win, $id=NULL,  $mainid=NULL)
	{
		$winparams = explode('_',$win);
		$modelClassName = '\\app\\modules\\purchase\\models\\'.ucfirst($winparams[0]).'Form'; //'\\app\\modules\\parties\\models\\'.
		$model = new $modelClassName;

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			return $this->redirect(['view', 'id' => $mainid]);
		} 
		else 
		{
			$showform = 'windows/_form_'.$winparams[0];
			return $this->renderPartial('windows/base_window',[
					'model' => $model,
					'showform' => $showform
			]);
		}
	}

	/**
	 * [actionWindow description]
	 * @param  [type] $id  [description]
	 * @param  [type] $win [description]
	 * @return [type]      [description]
	 */
	public function actionWindowoperations($id, $win, $mainid)
	{
		$winparams = explode('_',$win);
		$modelClassName = '\\app\\modules\\purchase\\models\\'.ucfirst($winparams[0]);
		$model = new $modelClassName;

		if($winparams[1]=='update' || $winparams[1]=='deleteajax'|| $winparams[1]=='approveajax'|| $winparams[1]=='rejectajax')
		{
			$model = $model->find($id);
		}

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			return $this->redirect(['view', 'id' => $mainid]);
		} 
		else 
		{
			$showform = '_form_compact_update';
			if($winparams[1]=='deleteajax'){
				$showform = '_form_delete';
			}
			if($winparams[1]=='update' || $winparams[1]=='deleteajax')
			{
				return $this->renderPartial('windows/base_window',[
						'model' => $model,
						'showform' => $showform
				]);
			}
		}
	}

	/**
	 * Updates an existing PurchaseOrder model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		//change layout
    $this->layout = '/main';
		$model = $this->findModel($id);

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			header('Content-type: application/json');
			echo Json::encode('DONE');
			exit();
			//return $this->redirect(['view', 'id' => $model->id]);
		} else {
			return $this->render('@app/modules/purchase/views/purchase-order/createrequest', [
				'model' => $model,
			]);
		}
	}

	/**
	 * [actionWorkflow description]
	 * @param  [type] $id [description]
	 * @return [type]     [description]
	 */
	public function actionWorkflow($id)
	{
		//change layout
		$this->layout = '/main';
		$model = $this->findGroupModel($id);
		return $this->render('@app/modules/purchase/views/purchase-order/workflow', [
			'model' => $model,
		]);
	}

	/**
	 * Deletes an existing PurchaseOrder model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		//$this->findModel($id)->delete();
		$date = new DateTime('now');
		$model = $this->findModel($id);
		$model->time_deleted = $date->format("U");
		$model->save();
		if (\Yii::$app->request->isAjax) {
					header('Content-type: application/json');
					echo Json::encode(['status'=>'DONE']);
					exit();
		}else{
			return $this->redirect(['/site/index']);
		}
	}

	/**
	 * Finds the PurchaseOrder model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return PurchaseOrder the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = PurchaseOrder::find($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}

	/**
	 * Finds the PurchaseOrderGroup model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return PurchaseOrder the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findGroupModel($id)
	{
		if (($model = PurchaseOrderGroup::find($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}

	/**
	 * returns the json for the dhtmlx grid
	 * @param  date  $un       YYYYMMDD
	 * @param  integer $posStart current position in grid scroll
	 * @param  integer $count    last record handed over
	 * @return JSON            		json object, see dhtmlx for more information
	 */
	public function actionDhtmlxgrid($un=NULL, $posStart=0, $count=0,$search=NULL,$mainid=NULL){
		$currentPage = 0;
		$pageSize = 100;
		
		if($posStart>0){
			$currentPage = round(($posStart / $pageSize),0);
		}

		$currentUserId = \Yii::$app->user->identity->id;		

		$query = new Query;
		if(is_Null($search))
		{
			$mainQuery = $query
			->select([
				'tbl_purchaseorder.id',
				'tbl_purchaseorder.status',
				'order_number', 
				'organisationName', 
				'contactName', 
				'FROM_UNIXTIME(tbl_purchaseorder.time_create,"%d-%m-%Y") AS CreationDate'
			])
			->from('tbl_purchaseorder')
			->leftJoin('tbl_contact','tbl_purchaseorder.contact_id = tbl_contact.id')
			->leftJoin('tbl_party','tbl_contact.party_id = tbl_party.id')
			->where('status = "created" AND tbl_purchaseorder.creator_id = '.$currentUserId.' AND tbl_purchaseorder.time_deleted IS NULL')
			->all(); //just all records
		}
		else
		{
			$mainQuery = $query
			->select([
				'tbl_purchaseorder.id',
				'tbl_purchaseorder.status',
				'order_number',
				'organisationName',
				'contactName', 
				'FROM_UNIXTIME(tbl_purchaseorder.time_create,"%d-%m-%Y") AS CreationDate'
			])
			->from('tbl_purchaseorder')
			->leftJoin('tbl_contact','tbl_purchaseorder.contact_id = tbl_contact.id')
			->leftJoin('tbl_party','tbl_contact.party_id = tbl_party.id')
			->where('order_number LIKE "%'.$search.'%" AND status = "created" AND tbl_purchaseorder.creator_id = '.$currentUserId.' AND tbl_purchaseorder.time_deleted IS NULL')
			->all(); 
		}
		$provider = new ArrayDataProvider([
			'allModels' => $mainQuery,
 			'sort' => [
 				'attributes' => ['CreationDate', 'order_number'],
 			],
 			'pagination' => [
 				'pageSize' => $pageSize,
 				'page' => $currentPage
 			],
 		]); 		

		//the grid header to pass over total count
		$totalcounter = 0;
		foreach($provider->getModels() AS $record){
			if(!is_null($record))
			{
				$record['deletelink'] = Url::to(['/purchase/purchase-order/windowoperations','id'=>$record['id'],'win'=>'purchaseOrder_deleteajax','mainid'=>0]);                
				$clean['rows'][]=['id'=>$record['id'],'data'=>array_values($record)];
				$totalcounter++;
			}
		}
		if($totalcounter == 0)
    {
      $clean['rows'][]=['id'=>0,'data'=>[]];
    }
		$clean['total_count']=PurchaseOrder::find()->where(['status'=>'created','time_deleted'=>'IS NULL']);
    $clean['pos']=$posStart;

		header('Content-type: application/json');
		echo Json::encode($clean);
		exit();
	}

}

modules/purchase/views/purchase-order/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\modules\purchase\models\PurchaseOrder $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="purchase-order-form">

	<?php $form = ActiveForm::begin(); ?>

		<?= $form->field($model, 'party_id')->textInput() ?>

		<?= $form->field($model, 'creator_id')->textInput() ?>

		<?= $form->field($model, 'time_deleted')->textInput() ?>

		<?= $form->field($model, 'time_create')->textInput() ?>

		<?= $form->field($model, 'order_number')->textInput(['maxlength' => 200]) ?>

		<div class="form-group">
			<?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
		</div>

	<?php ActiveForm::end(); ?>

</div>

modules/purchase/views/purchase-order/_form_delete.php
<?php

use kartik\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\modules\purchase\models\PurchaseOrderLine $model
 * @var yii\widgets\ActiveForm $form
 */

$script = <<<SKRIPT

$('.deletecancelbutton').on('click',function(event){
  $('#applicationModal').modal('hide');
  event.preventDefault();
});

$('.deletedeletebutton').on('click',function(event){  
  var delURL = $(this).attr('href');
  $.ajax({
    url : delURL,
    type : "GET",
    dataType : "json",
  }).success(function(){
    $('#applicationModal').modal('hide');
    window.doOnFilterStart(1,'');
  });
  event.preventDefault();
});

SKRIPT;

$this->registerJs($script);

?>

<div class="alert alert-danger">
  
  <h1><?= Html::Icon('exclamation-sign'); ?> <?= \Yii::t('app','Caution, you are planing to delete a record!'); ?></h1>
  <p>
    <?= Html::a(\Yii::t('app','Cancel'), ['cancel', 'id' => $model->id], ['class' => 'btn btn-primary deletecancelbutton']) ?>
    <?php echo Html::a(\Yii::t('app','Delete'), ['delete', 'id' => $model->id], [
      'class' => 'btn btn-danger deletedeletebutton'
    ]); ?>
  </p>

</div>

modules/purchase/views/purchase-order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\modules\purchase\models\PurchaseOrderSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="purchase-order-search">

	<?php $form = ActiveForm::begin([
		'action' => ['index'],
		'method' => 'get',
	]); ?>

		<?= $form->field($model, 'id') ?>

		<?= $form->field($model, 'party_id') ?>

		<?= $form->field($model, 'order_number') ?>

		<?= $form->field($model, 'creator_id') ?>

		<?= $form->field($model, 'time_deleted') ?>

		<?php // echo $form->field($model, 'time_create') ?>

		<div class="form-group">
			<?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
			<?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
		</div>

	<?php ActiveForm::end(); ?>

</div>

modules/purchase/views/purchase-order/createrequest.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var yii\web\View $this
 * @var app\modules\purchase\models\PurchaseOrder $model
 */

$this->title = 'Request PO';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php
//all that has to do with the grid
$target = Url::to(array('/purchase/purchase-order-line/update','id'=>''));
$gridURL = Url::to(['/purchase/purchase-order-line/dhtmlxgrid','un'=> date('Ymd'),'mainid'=>$model->id]);

$gridJS = <<<GRIDJS

$.fn.modal.Constructor.prototype.enforceFocus = function() {};

calculateFooterValues = function() {
    var nrTA = document.getElementById("nr_ta");
    var myResult = sumColumn(7);
    nrTA.innerHTML = addCommas(myResult.toFixed(2));
    return true;
}

sumColumn = function(ind) {  
    var out = 0;
    for (var i = 0; i < dhtmlxPurchaseRequestGrid.getRowsNum(); i++) {
        out += parseFloat(dhtmlxPurchaseRequestGrid.cells2(i, ind).getValue());
    }
    return out;
}

doOnFilterStart = function(indexes,values){
  $.ajax("$gridURL&search="+values).
  success(function(data){      
      dhtmlxPurchaseRequestGrid.clearAll();
      dhtmlxPurchaseRequestGrid.parse(data,"json");
      calculateFooterValues();
      dhtmlxPurchaseRequestGrid.groupBy(0,["#title","#cspan","#cspan","#cspan","#stat_total","","","#stat_total","","",""]);
      dhtmlxPurchaseRequestGrid.setNumberFormat('0,000.00',4);
      dhtmlxPurchaseRequestGrid.setNumberFormat('0,000.00',5);
      dhtmlxPurchaseRequestGrid.setNumberFormat('0,000.00',7); 
    }
  );
}

$('#SubmitPurchaseRequest').on('click',function(event){
  myUrl = $(this).attr('href');
  $('#applicationModal').modal('show');
  $('#applicationModal div.modal-header h4').html('Window');
  $('#applicationModal div.modal-body').load(myUrl);
  return false;
});

$('#StartpageForwarder').on('click',function(event){
  myUrl = $(this).attr('href');
  $('#applicationModal').modal('show');
  $('#applicationModal div.modal-header h4').html('Window');
  $('#applicationModal div.modal-body').load(myUrl);
  return false;
});


GRIDJS;
$this->registerJs($gridJS);

?>

<div class="purchase-order-create">

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <?= Yii::t('app','Purchase Request by') ?> <?= $model->contact->contactName; ?> <?= \Yii::t('app','on'); ?> <b><?= date('d-m-Y',$model->time_create); ?></b>
        <div class="pull-right">
          PR# <?= $model->id; ?> Status: <span class="badge"><?= $model->status; ?></span>
        </div>
      </div>
      <div class="panel-body">
        <?php 

        if($model->status == 'created')
        {
          echo $this->render('@app/modules/purchase/views/purchase-order-line/_form_compact', [
            'model' => new app\modules\purchase\models\PurchaseOrderLine,
            'purchaseorder_id' => $model->id,
          ]); 
        }

        ?>

        <?php echo $this->render('@app/modules/purchase/views/purchase-order/blocks/order_block', [
            'model' => $model,
            'gridURL' => $gridURL
        ]); ?>        
        <hr>
        <div class="row">
          <div class="col-md-12">
          <?php

          if($model->status == 'created'):
            echo Html::a(\Yii::t('app','Submit'), ['/purchase/default/window', 'id' => $model->id,'win'=>'purchaseOrder_submit'], [
              'class' => 'btn btn-success pull-right',
              'id'    => 'SubmitPurchaseRequest'
            ]);
          ?>
            
          <div class="pull-right">&nbsp;</div>
  
          <?php
            echo Html::a(\Yii::t('app','Save'), ['/purchase/default/window', 'id' => $model->id,'win'=>'purchaseOrder_save'], [
              'class' => 'btn btn-primary pull-right',
              'id'    => 'StartpageForwarder'
            ]);            
          
          endif;
          ?>
          </div>
        </div>
        <hr>
        <?php 
          if(class_exists('\app\modules\dms\widgets\PortletDms') && Yii::$app->user->identity->isAdvanced){
            echo \app\modules\dms\widgets\PortletDms::widget(array(
              'module'=>\app\modules\dms\models\Dmsys::MODULE_PURCHASE,
              'id'=>$model->id,
            )); 
          }
        ?>
    </div>
  </div>
  </div>
</div>

</div>

modules/purchase/views/purchase-order/pending.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var yii\web\View $this
 * @var app\modules\purchase\models\PurchaseOrder $model
 */

$this->title = 'Pending requested POs';
$this->params['breadcrumbs'][] = $this->title;

?>

<?php
//all that has to do with the grid
$gridURL = Url::to(['/purchase/purchase-order-group/dhtmlxgrid','un'=> date('Ymd'),'mainid'=>$model->id]);

$gridJS = <<<GRIDJS

$.fn.modal.Constructor.prototype.enforceFocus = function() {};

calculateFooterValues = function() {
    var nrTA = document.getElementById("nr_ta");
    var myResult = sumColumn(6);
    nrTA.innerHTML = addCommas(myResult.toFixed(2));
    return true;
}

sumColumn = function(ind) {  
    var out = 0;
    for (var i = 0; i < dhtmlxPurchaseRequestGrid.getRowsNum(); i++) {
        out += parseFloat(dhtmlxPurchaseRequestGrid.cells2(i, ind).getValue());
    }
    return out;
}

GRIDJS;
$this->registerJs($gridJS);

?>

<div class="purchase-order-create">

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <?= Yii::t('app','Purchase Request by') ?> <?= $model->contact->contactName; ?> <?= \Yii::t('app','on'); ?> <b><?= date('d-m-Y',$model->time_create); ?></b>
        &nbsp;<?= \Yii::t('app','waiting for approval'); ?>
        <div class="pull-right">
          PR# <?= $model->id; ?> Status: <span class="badge"><?= $model->status; ?></span>
        </div>
      </div>
      <div class="panel-body">
        
        <?php echo $this->render('@app/modules/purchase/views/purchase-order/blocks/pending_block', [
            'model' => $model,
            'gridURL' => $gridURL
        ]); ?>        
        
        <hr>

        <div class="form-group">
          
          <div class="pull-right">&nbsp;</div>

          <?php
            echo Html::a(\Yii::t('app','Back'), ['/site/index'], [
              'class' => 'btn btn-primary pull-right',
              'id'    => 'StartpageForwarder'
            ]);
          ?>

        </div>
        <div class="clearfix"></div>
        <hr>
        <?php 
          if(class_exists('\app\modules\dms\widgets\PortletDms') && Yii::$app->user->identity->isAdvanced){
            echo \app\modules\dms\widgets\PortletDms::widget(array(
              'module'=>\app\modules\dms\models\Dmsys::MODULE_PURCHASE,
              'id'=>$model->id,
            )); 
          }
        ?>
    </div>
  </div>
  </div>
</div>

</div>

modules/purchase/views/purchase-order/purchase.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var yii\web\View $this
 * @var app\modules\purchase\models\PurchaseOrder $model
 */

$this->registerAssetBundle('yii\widgets\ActiveFormAsset');
$this->registerAssetBundle('yii\validators\ValidationAsset');
$this->registerAssetBundle('kartik\widgets\Select2Asset');
$this->registerAssetBundle('kartik\widgets\TypeaheadAsset');
//$this->registerAssetBundle('kartik\widgets\Typeahead2Asset');
$this->registerAssetBundle('kartik\widgets\DatePickerAsset');


$this->title = 'Approve requested PO';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php
//all that has to do with the grid
$target = Url::to(array('/purchase/purchase-order-line/update','id'=>''));
$gridURL = Url::to(['/purchase/default/dhtmlxgridegpdetail','un'=> date('Ymd'),'mainid'=>$model->id]);

$gridJS = <<<GRIDJS

$.fn.modal.Constructor.prototype.enforceFocus = function() {};

calculateFooterValues = function() {
    var nrTA = document.getElementById("nr_ta");
    var myResult = sumColumn(6);
    nrTA.innerHTML = addCommas(myResult.toFixed(2));
    return true;
}

sumColumn = function(ind) {  
    var out = 0;
    for (var i = 0; i < dhtmlxPurchaseRequestGrid.getRowsNum(); i++) {
        out += parseFloat(dhtmlxPurchaseRequestGrid.cells2(i, ind).getValue());
    }
    return out;
}

doOnFilterStart = function(indexes,values){
  $.ajax("$gridURL&search="+values).
  success(function(data){      
      dhtmlxPurchaseRequestGrid.clearAll();
      dhtmlxPurchaseRequestGrid.parse(data,"json");
      calculateFooterValues();
      dhtmlxPurchaseRequestGrid.setNumberFormat('0,000.00',4);
      dhtmlxPurchaseRequestGrid.setNumberFormat('0,000.00',5);
      dhtmlxPurchaseRequestGrid.setNumberFormat('0,000.00',7); 
    }
  );
}

doOnApproval = function(rId,cInd,state){
  alert(rId);
  alert(state);
}

refreshAllGrids = function(){
  doOnFilterStart(1);
}

$('#SubmitPurchaseRequest').on('click',function(event){
  myUrl = $(this).attr('href');
  $('#applicationModal').modal('show');
  $('#applicationModal div.modal-header h4').html('Window');
  $('#applicationModal div.modal-body').load(myUrl);
  return false;
});

GRIDJS;
$this->registerJs($gridJS);

?>

<div class="purchase-order-create">

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <?= Yii::t('app','Manage purchase') ?> <?= $model->contact->contactName; ?> <?= \Yii::t('app','on'); ?> <b><?= date('d-m-Y',$model->time_create); ?></b>
        &nbsp;<?= \Yii::t('app','needs your approval'); ?>
        <div class="pull-right">
          PR# <?= $model->id; ?> Status: <span class="badge"><?= $model->status; ?></span>
        </div>
      </div>
      <div class="panel-body">
        <?php echo $this->render('@app/modules/purchase/views/purchase-order/blocks/egp_block', [
            'model' => $model,
            'gridURL' => $gridURL
        ]); ?>
        <hr>
        <div class="form-group">
          <?php
            echo Html::a(\Yii::t('app','Submit'), ['/purchase/purchase-order-group/window','win'=>'purchaseOrderGroup_purchasesubmit' ,'id' => $model->id], [
              'class' => 'btn btn-success pull-right',
              'id'    => 'SubmitPurchaseRequest'
            ]);
          ?>
            
          <div class="pull-right">&nbsp;</div>
  
          <?php
            echo Html::a(\Yii::t('app','Save'), ['/site/index'], [
              'class' => 'btn btn-primary pull-right',
              'id'    => 'StartpageForwarder'
            ]);
          ?>
        </div>

        <hr>
        <?php 
          if(class_exists('\app\modules\dms\widgets\PortletDms') && Yii::$app->user->identity->isAdvanced){
            echo \app\modules\dms\widgets\PortletDms::widget(array(
              'module'=>\app\modules\dms\models\Dmsys::MODULE_PURCHASE,
              'id'=>$model->id,
            )); 
          }
        ?>
    </div>
  </div>
  </div>
</div>

</div>