modules/parties/models/Party.php
<?php

namespace app\modules\parties\models;

use \DateTime;

/**
 * New party class, adapted by Frenzel Gmbh 2013
 *
 * @author Philipp Frenzel <philipp@frenzel.net>
 * @version 0.1
 */

/**
 * This is the model class for table "tbl_party".
 *
 * @property integer $id
 * @property string $organisationName
 * @property string $partyNote
 * @property string $taxNumber
 * @property string $registrationNumber
 * @property integer $registrationCountryCode
 * @property integer $party_type
 * @property string $system_key
 * @property string $system_name
 * @property integer $system_upate
 * @property integer $creator_id
 * @property integer $time_deleted
 * @property integer $time_create
 *
 * @property Address[] $addresses
 * @property Contact[] $contacts
 */
class Party extends \yii\db\ActiveRecord
{

	/**
	* Here I create the constants for the party types
	*
	* @property party_type
	*/

  const TYPE_VENDOR  	 = 1;
  const TYPE_CUSTOMER  = 2;
  const TYPE_INTERNAL  = 3;

  public static $pTypes = [
    self::TYPE_VENDOR   => 'Vendor',
    self::TYPE_CUSTOMER => 'Customer',
    self::TYPE_INTERNAL => 'System'
  ];

  public static function getPartyTypeOptions()
  {
  	return self::$pTypes;
  }

  public function getPartyTypeAsString($type=NULL)
  {
    if(is_NULL($type))
    {
      $type = $this->party_type;
    }
    $options = self::getPartyTypeOptions();
    return isset($options[$type]) ? $options[$type] : '';
  }

	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'tbl_party';
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['organisationName'], 'required'],
			[['partyNote','taxNumber'], 'string'],
			[['registrationCountryCode', 'party_type', 'system_upate', 'creator_id', 'time_deleted', 'time_create'], 'integer'],
			[['organisationName'], 'string', 'max' => 255],
			[['taxNumber', 'registrationNumber', 'system_key', 'system_name'], 'string', 'max' => 100]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
      'id'                      => \Yii::t('app','ID'),
      'organisationName'        => \Yii::t('app','Organisation Name'),
      'partyNote'               => \Yii::t('app','Party Note'),
      'taxNumber'               => \Yii::t('app','Tax Number'),
      'registrationNumber'      => \Yii::t('app','Registration Number'),
      'registrationCountryCode' => \Yii::t('app','Registration Country Code'),
      'party_type'              => \Yii::t('app','Party Type'),
      'partyTypeAsString'       => \Yii::t('app','Party Type'),
      'system_key'              => \Yii::t('app','System Key'),
      'system_name'             => \Yii::t('app','System Name'),
      'system_upate'            => \Yii::t('app','System Upate'),
      'creator_id'              => \Yii::t('app','Creator ID'),
      'time_deleted'            => \Yii::t('app','Time Deleted'),
      'time_create'             => \Yii::t('app','Time Create'),
		];
	}

	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getAddresses()
	{
		return $this->hasMany(Address::className(), ['party_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveRelation
	 */
	public function getContacts()
	{
		return $this->hasMany(Contact::className(), ['party_id' => 'id']);
	}

  /**
   * @return \yii\db\ActiveRelation
   */
  public function getCountry()
  {
    return $this->hasOne(Country::className(), ['id' => 'registrationCountryCode']);
  }

  /**
   * @return string name of country
   */
  public function getCountryName()
  {
    return $this->country->country_name;
  }

  /**
   * [beforeSave description]
   * @param  [type] $insert [description]
   * @return [type]         [description]
   */
  public function afterSave($insert)
  {
    $date = new DateTime('now');
    if($this->isNewRecord)
    {
      if(\Yii::$app->user->isGuest)
      {
        $this->creator_id = 0; //external system writer
      }
      else
      {
        $this->creator_id = \Yii::$app->user->identity->id;
      }
      if(is_null($this->party_type) OR $this->party_type == '')
      {
        $this->party_type = self::TYPE_VENDOR;
      }      
    }
    if($this->system_name == '' OR is_Null($this->system_name))
    {
      $this->system_name = 'PUREPO';
      $this->system_key = $this->id;
    }
    if(is_null($this->time_create))
    {
      $this->time_create = $date->format("U");
    }
    $this->system_upate = $date->format("U");
    return parent::afterSave($insert);    
  }

}

modules/parties/controllers/PartyController.php
<?php

namespace app\modules\parties\controllers;

use app\modules\parties\models\Party;
use app\modules\parties\models\PartySearch;

use Yii;
use yii\db\Query;
use yii\data\ArrayDataProvider;
use app\modules\app\controllers\AppController;
use yii\web\NotFoundHttpException;
use yii\web\VerbFilter;
use yii\helpers\Json;

/**
 * PartyController implements the CRUD actions for Party model.
 */
class PartyController extends AppController
{

	public function behaviors()
	{
		return [
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
					'importer' => ['post'],
				],
			],
			'AccessControl' => [
				'class' => '\yii\web\AccessControl',
				'rules' => [
					[
						'allow'=>true,
						'actions'=>['importer'],
						'roles'=>['?'],
					],
					array(
						'allow'=>true,
						'actions'=>array('update','create','index','view','delete','dhtmlxgrid','window','jsonlist'),
				    'roles'=>array('@'),
					)
				]
			],
			'disableCSRF' => [
        // required to disable csrf validation on OpenID requests
        'class' => \app\modules\app\behaviours\CSRFdisableBehaviour::className(),
        'only' => array('importer'),
      ],
		];
	}

	/**
	 * Lists all Party models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		return $this->render('index');
		/*$searchModel = new PartySearch;
		$dataProvider = $searchModel->search($_GET);

		return $this->render('index', [
			'dataProvider' => $dataProvider,
			'searchModel' => $searchModel,
		]);*/
	}

	/**
	 * [actionWindow description]
	 * @param  [type] $id  [description]
	 * @param  [type] $win [description]
	 * @return [type]      [description]
	 */
	public function actionWindow($id, $win, $mainid)
	{
		$winparams = explode('_',$win);
		$modelClassName = '\\app\\modules\\parties\\models\\'.ucfirst($winparams[0]);
		$model = new $modelClassName;

		if($winparams[1]=='update')
		{
			$model = $model->find($id);
		}

		if ($model->load(\Yii::$app->request->post()) && $model->save()) {
			return $this->redirect(['view', 'id' => $mainid]);
		} else {
			if(ucfirst($winparams[0]) != 'Party')
			{
				$model->party_id = $mainid; //assign the party id upfront			
			}
			$showform = '../'.$winparams[0].'/_form';
			return $this->renderPartial('windows/base_window',[
					'model' => $model,
					'showform' => $showform
			]);
		}
	}

	/**
	 * Displays a single Party model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView($id)
	{
		return $this->render('view_online', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	 * Creates a new Party model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate()
	{
		$model = new Party;

		if ($model->load(\Yii::$app->request->post()) && $model->save()) {
			if (\Yii::$app->request->isAjax) {
				header('Content-type: application/json');
				echo Json::encode(['status'=>'DONE','model'=>$model]);
				exit();
			}else{
				return $this->redirect(['view', 'id' => $model->id]);
			}
		} else {
			return $this->render('create', [
				'model' => $model,
			]);
		}
	}

	/**
	 * Updates an existing Party model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);

		if ($model->load(\Yii::$app->request->post()) && $model->save()) {
			return $this->redirect(['view', 'id' => $model->id]);
		} else {
			return $this->render('update', [
				'model' => $model,
			]);
		}
	}

	/**
	 * Deletes an existing Party model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		$this->findModel($id)->delete();
		return $this->redirect(['index']);
	}

	/**
	 * Finds the Party model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return Party the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = Party::find($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}

	/**
	 * returns the json for the dhtmlx grid
	 * @param  date  $un       YYYYMMDD
	 * @param  integer $posStart current position in grid scroll
	 * @param  integer $count    last record handed over
	 * @return JSON            		json object, see dhtmlx for more information
	 */
	public function actionDhtmlxgrid($un=NULL, $posStart=0, $count=0,$search=NULL){
		$currentPage = 0;
		$pageSize = 100;
		
		if($posStart>0){
			$currentPage = round(($posStart / $pageSize),0);
		}

		$query = new Query;
		if(is_Null($search))
		{
			$mainQuery = $query->select('tbl_party.id AS id,system_name, system_key, organisationName,taxNumber,country_code')
			->from('tbl_party')
      ->leftJoin('tbl_country', 'tbl_country.id = tbl_party.registrationCountryCode')
			->all(); //just all records
		}
		else
		{
			$mainQuery = $query->select('tbl_party.id AS id,system_name, system_key,organisationName,taxNumber,country_code')
			->from('tbl_party')
      ->leftJoin('tbl_country', 'tbl_country.id = tbl_party.registrationCountryCode')
			->where('organisationName LIKE "%'.$search.'%"')
			->all(); 
		}
		$provider = new ArrayDataProvider([
			'allModels' => $mainQuery,
 			'sort' => [
 				'attributes' => ['id', 'organisationName'],
 			],
 			'pagination' => [
 				'pageSize' => $pageSize,
 				'page' => $currentPage
 			],
 		]);

		//the grid header to pass over total count
		$clean = ['total_count'=>Party::find()->count(),'pos'=>$posStart];
		foreach($provider->getModels() AS $record){
			if(!is_null($record))
			{
				$clean['rows'][]=['id'=>$record['id'],'data'=>array_values($record)];
			}
		}

		header('Content-type: application/json');
		echo Json::encode($clean);
		exit();
	}

	/**
	 * [actionJsonlist description]
	 * @param  [type] $search Text for the lookuk
	 * @return [type]         [description]
	 */
	public function actionJsonlist($search = NULL,$id = NULL)
	{
		header('Content-type: application/json');
		$clean['more'] = false;

		$query = new Query;
		if(!is_Null($search))
		{
			$mainQuery = $query->select('id, organisationName AS text')
				->distinct()
				->from('tbl_party')
				->where('UPPER(organisationName) LIKE "%'.strtoupper($search).'%"');

			$command = $mainQuery->createCommand();
			$rows = $command->queryAll();
			$clean['results'] = array_values($rows);
		}
		else
		{			
			if(!is_null($id))
			{
				$clean['results'] = ['id'=> $id,'text' => Party::find($id)->organisationName];
			}else
			{
				$clean['results'] = ['id'=> 0,'text' => 'None found'];
			}
		}
		echo Json::encode($clean);
		exit();
	}

	/**
	 * [actionImporter description]
	 * @return [type] [description]
	 */
	public function actionImporter(){
		//checks for update/create a new party
		$model = $this->checkExisting($_POST['Party']['system_name'],$_POST['Party']['system_key']);
		$model->load(Yii::$app->request->post());
		$model->registrationCountryCode = \app\modules\parties\models\Country::getCountryIdByCode($model->registrationCountryCode);
		$model->save();

		//adding a new address to the party
		if(isset($_POST['Address']))
		{
			$address = $this->checkExistingAddress($_POST['Address']['system_name'],$_POST['Address']['system_key'],$model->id);
			$address->load(\Yii::$app->request->post());
			$address->party_id = $model->id;
			if($address->addressLine != '' AND $address->cityName != '')
			{
				$address->save();
			}
		}
		exit();
	}

	/**
	 * checks if a party record already exists so it will be updated
	 * @param  VARCHAR $system_name reference to the system that tries to import the record
	 * @param  VARCHAR $system_key  the internal key within the foreign system referenced by system_name
	 * @return OBJECT wether an existing or new party model, that will be filled with the post variables
	 */
	private function checkExisting($system_name,$system_key)
	{
		$testModel = Party::find()->where(['system_name' => $system_name, 'system_key' => $system_key])->One();
		if(is_object($testModel))
		{
			return $testModel;
		}
		$model = new Party;
		return $model;	
	}

	/**
	 * checks if a address record already exists so it will be updated
	 * @param  VARCHAR $system_name reference to the system that tries to import the record
	 * @param  VARCHAR $system_key  the internal key within the foreign system referenced by system_name
	 * @return OBJECT wether an existing or new address model, that will be filled with the post variables
	 */
	private function checkExistingAddress($system_name,$system_key,$party_id)
	{
		$testModel = Address::find()->where([
			'system_name' => $system_name, 
			'system_key' => $system_key,
			'party_id'=>$party_id
		])->One();
		if(is_object($testModel))
		{
			return $testModel;
		}
		$model = new Address;
		return $model;	
	}

}

modules/parties/views/party/blocks/block_address.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

use kartik\icons\Icon;

/**
 * @var app\modules\parties\models\Party $model
 */

$modalJS = <<<MODALJS
$('#window_address_add').on('click',myModalWindow);
MODALJS;
$this->registerJs($modalJS);

?>

<div class="nav" role="navigation">
  
  &nbsp;
  <?php echo Html::a(\Yii::t('app','Create'), ['window', 'id' => $model->id, 'win'=>'address_create','mainid'=>$model->id], [
    'class' => 'btn btn-info navbar-btn navbar-right',
    'id' => 'window_address_add'
  ]); ?>
</div>


<?php foreach($model->addresses AS $address): ?>

<div class="row">
  <div class="col-md-1">
    <?= Icon::show('globe', ['class'=>'fa fa-2x'], Icon::FA);?>
  </div>
  <div class="col-md-7">
    <address>
      <abbr title="PO Box">Po Box:</abbr> <?= $address->postBox ?><br>
      <?= $address->addressLine ?> <?= $address->streetDescription ?><br>
      <?= $address->postCode ?> <?= $address->cityName ?> <br>
      <?= $address->countryName ?>
    </address>
  </div>
  <div class="col-md-4">
    <?php 
      echo Html::a(\Yii::t('app','Edit'), ['window', 'id' => $address->id, 'win'=>'address_update','mainid'=>$model->id], [
        'class' => 'btn btn-default navbar-btn navbar-right',
        'id' => 'window_address_edit'.$address->id
      ]); 

      $actionjs = new yii\web\JsExpression("$('#window_address_edit".$address->id."').on('click',myModalWindow);");
      $this->registerJs($actionjs);
    ?>
  </div>
</div>
<hr>
  

<?php endforeach; ?>

modules/parties/views/party/blocks/block_contact.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

use yii\widgets\DetailView;

use yiidhtmlx\Grid;

/**
 * @var app\modules\parties\models\Party $model
 */

$modalJS = <<<MODALJS
$('#window_contact_edit').on('click',myModalWindow);
$('#window_contact_add').on('click',myModalWindow);

MODALJS;
$this->registerJs($modalJS);

//all that has to do with the grid
$target = Url::to(array('/parties/contact/view','id'=>''));
$gridURL = Url::to(['/parties/contact/dhtmlxgrid','un'=> date('Ymd'),'party_id'=>$model->id]);
$gridJS = <<<GRIDJS

function doOnFilterStart(indexes,values){
  $.ajax("$gridURL&search="+values).
  success(function(data){
      dhtmlxContactGrid.clearAll();
      dhtmlxContactGrid.parse(data,"json");
    }
  );  
}
GRIDJS;
$this->registerJs($gridJS);

?>

<div class="nav" role="navigation">
  <?php /*echo Html::a('edit', ['window', 'id' => $model->id, 'win'=>'contact_update','mainid'=>$model->id], [
    'class' => 'btn btn-default navbar-btn navbar-right',
    'id' => 'window_contact_edit'
  ]);*/?>
  &nbsp;
  <?php echo Html::a(\Yii::t('app','Create'), ['window', 'id' => $model->id, 'win'=>'contact_create','mainid'=>$model->id], [
    'class' => 'btn btn-info navbar-btn navbar-right',
    'id' => 'window_contact_add'
  ]); ?>
</div>


<?php
  echo Grid::widget(
    [
    'clientOptions'=>[
        'parent'      => 'ContactGrid',
        'image_path'  => Yii::$app->AssetManager->getBundle('yiidhtmlx\GridObjectAsset')->baseUrl."/dhtmlxGrid/imgs/",
        'auto_height' => false,
        'auto_width'  => false,
        'smart'       => true,
        'skin'        => "dhx_terrace",       
        'columns' => [
          ['label'=>'id','width'=>'40','type'=>'ro'],
          ['label'=>[Yii::t('app','contactName'),'#text_filter'],'type'=>'ed'],
          ['label'=>[Yii::t('app','Department')],'type'=>'ed'],
          ['label'=>[Yii::t('app','Email')],'type'=>'ed','width'=>'130'],
          ['label'=>[Yii::t('app','Phone')],'type'=>'ed','width'=>'90'],
          ['label'=>[Yii::t('app','Edit')],'type'=>'modalbutton','width'=>'80'],
        ],
      ],
      'enableSmartRendering' => true,
      'options'=>[
        'id'    => 'ContactGrid',
        'height' => '300px',  
        'width'  => '100%',            
      ],
      'clientDataOptions'=>[
        'type'=>'json',
        'url'=> $gridURL
      ],
      'clientEvents'=>[
        'onFilterStart' => 'doOnFilterStart'
      ]   
    ]
  );
?>

modules/parties/views/party/blocks/block_party.php
<?php

use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\widgets\DetailView;

/**
 * @var app\modules\parties\models\Party $model
 */

?>

<div class="nav" role="navigation">
  <?php echo Html::a(\Yii::t('app','Edit'), ['window', 'id' => $model->id, 'win'=>'party_update','mainid'=>$model->id], [
    'class' => 'btn btn-primary navbar-btn navbar-right',
    'id' => 'window_party_edit'
  ]); ?>
</div>


<div class="row">
  <div class="col-md-6">
    <?php echo DetailView::widget([
    'model' => $model,
    'attributes' => [
      'partyTypeAsString',
      //'organisationName',
      //'partyNote:ntext',
      'taxNumber',
      'registrationNumber',
      'countryName'
    ],
]); ?>
  </div>
  <div class="col-md-6">
    <blockquote>
      <small><?= \Yii::t('app','Note'); ?></small>
      <p>
        <?= HtmlPurifier::process($model->partyNote); ?>
      </p>
    </blockquote>
  </div>
</div>

modules/parties/views/party/blocks/block_system.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var app\modules\parties\models\Party $model
 */

?>

<h4><?= Yii::t('app','System Info') ?></h4>

<?php echo DetailView::widget([
    'model' => $model,
    'attributes' => [
      'id',
      'system_key',
      'system_name',
      'system_upate:datetime'
    ],
  ]); ?>